# Generated by Django 4.0.4 on 2022-04-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_test_delete_logininfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
