# Generated by Django 4.0.4 on 2022-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_logininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='账号名称'),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
