# Generated by Django 4.0.4 on 2022-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_logininfo_name_alter_logininfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=20, verbose_name='用户密码'),
        ),
    ]
